<?php if(isset($this->errorlogin)) { $error = $this->errorlogin; } ?>
<!DOCTYPE html>
<html>
	<head>
		<title>Admin gate</title>
		<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
		<script src="http://cdn.jsdelivr.net/jquery.validation/1.14.0/jquery.validate.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
		<script src="https://raw.githubusercontent.com/dreyescat/bootstrap-rating/master/bootstrap-rating.min.js"></script>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
		<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
	</head>
	<body>
		<style>
			body
			{
				width: 100%;
			}
		</style>
		<form method="post" id="login_form">
			<div id="main" class="col-lg-4 col-lg-offset-4 container-fluid">
				
				<div class="a-formcon col-centered">
					<div class="panel panel-primary">
					  <div class="panel-heading">
					    <h3 class="panel-title">Login</h3>
					  </div>
					  <div class="panel-body">
					  	
						<div class="input-group">
							<span class="input-group-addon" id="basic-addon1"><i class="fa fa-envelope fa-fw"></i></span>
							<input type="email" id="email_input" name="email_input" aria-describedby="basic-addon1"  class="form-control" required>
						</div>
						
						<div class="input-group">
							<span class="input-group-addon" id="basic-addon1"><i class="fa fa-key fa-fw"></i></span>
							<input type="password" id="password_input" name="password_input" aria-describedby="basic-addon1"  class="form-control" required>
						</div>

 						<div style="<?php if(isset($error)) { echo "display: block;"; } else { echo "display: none;"; } ?>" id="login_error" class="alert alert-danger" role="alert"><?php if(isset($error)) { echo $error; } ?></div>
				    	<div id="buttons">
				    		<button id="login_button" type="submit" class="btn btn-primary">Login</button>
				    	</div>
					  </div>
					</div>
				</div>
				
			</div>
		</form>
	</body>
</html>