<?php if(!$this->CheckLogin()) { ?>
<style>
	#register{
		margin-left: 35%;
		margin-right: 35%;
	}
	.input-group{
		margin-bottom: 2%;
	}
</style>
<div id="register">
	<form method="POST">
		<h3>Register</h3>
  <div class="input-group">
    <div class="input-group-addon"><i class="fa fa-user"></i></div>
    <input name="username" type="text" class="form-control" id="username_input" placeholder="Username">
  </div>
  <div class="input-group">
    <div class="input-group-addon"><i class="fa fa-envelope"></i></div>
    <input name="email" type="email" class="form-control" id="email_input" placeholder="Email">
  </div>
  <div class="input-group">
    <div class="input-group-addon"><i class="fa fa-key"></i></div>
    <input name="password" type="password" class="form-control" id="password_input" placeholder="Password">
  </div>
  <button type="submit" class="btn btn-default">Register</button>
  <?php if(isset($this->registererror)) { ?>
  	
  	<div class="alert alert-danger alert-dismissible" role="alert">
  		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  		<?php echo $this->registererror; ?></div>
  	<?php } ?>
</form>
</div>

<?php } else{
	
} ?>
