
<?php //phpinfo(); ?>

<style>
	.no-close .ui-dialog-titlebar-close
	{
		display: none;
	}
	
	#div-list-series, #div-list-films
	{
		margin-left: 10px;
		margin-right: 10px;
		display: flex;
		flex-wrap: wrap;
	}
</style>
<script type="text/javascript">

$(document).ready(function (){
	
	$(document).on("click", ".serie_link", function(){
		window.location.href = "/default/series/show/id/" + $(this).parent().find(":input").val();
	});
	
	$(document).on("click", ".movie_link", function(){
		window.location.href = "/default/films/show/id/" + $(this).parent().find(":input").val();
	});
	
	$(document).on("click", ".quickview-serie-button", function(e){
			$("#dialog-showinfo").dialog('open');
                $.ajax({
                    type: "POST",
                    url: "/default/index/getserieinfo/id_serie/" + $(this).parent().find(":input").val(),
                    dataType: "json",
                    success: function(data, status){
                        if(data.result == "success")
                        {
                           $("#dialog-showinfo").dialog('option', 'title', data.srs_title);
                           $("#d-title").html(data.srs_title);
                           $("#d-description").html(data.srs_description);
                        }
                    }
                });
	});
	
	$(document).on("click", ".quickview-film-button", function(){
		$("#dialog-showinfo").dialog('open');
			$.ajax({
				type: "POST",
                url: "/default/index/getfilminfo/id_film/" + $(this).parent().find(":input").val(),
                dataType: "json",
                success: function(data, status){
                    if(data.result == "success")
                    {
	                     $("#dialog-showinfo").dialog('option', 'title', data.mvs_title);
	                     $("#d-title").html(data.mvs_title);
	                     $("#d-description").html(data.mvs_description);
                    }
              	}
                   
			});
	});
	
	$("#dialog-showinfo").dialog({
		dialogClass: "no-close",
        autoOpen: false,
        height: 600,
        width: 400,
        modal: true,
        draggable: false,
        resizable: false,
        title: "Informatie",
		buttons:[{
			text: "Annuleren",
			icons:{
				primary: "ui-icon-heart"
			},
			click:function(){
				$(this).dialog("close");
			
			}
		}]
	});
	
	$('.quickview-button').button();
	
	refreshserieslist();
	refreshmovieslist();
	
	function refreshserieslist()
	{
		$("#div-list-series").load('/default/index/serieslist');
	}
	
	function refreshmovieslist()
	{
		$("#div-list-films").load('/default/index/filmlist');
	}
});
</script>
<div id="main">
	<h1>Series</h1>
	<div id="div-list-series">
		
	</div>
	
	<h1>Films</h1>
	<div id="div-list-films">
		
	</div>
</div>
<div id="dialog-showinfo">
	<div id="left">
		<img id="d-image" src="">

	</div>
	<div id="right">
		<p id="d-title"></p>
	</div>
</div>
