<?php

/**
 * AlbumMeta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AlbumMeta extends BaseAlbumMeta
{
    /**
     * @param integer $id
     * @return Doctrine_Collection|Doctrine_Collection_OnDemand|Doctrine_Record|int|mixed|null
     * @throws Exception
     */
    public static function LoadEntity($id)
    {
        $metaTable = Doctrine_Core::getTable("AlbumMeta");
        $meta = $metaTable->find($id);
        if(empty($meta))
        {
           throw new Exception("AlbumMeta::LoadEntity: No entity found for identifier " . $id);
        }
        return $meta;
    }

    /**
     * @param integer $album_id
     * @return bool|Doctrine_Record|mixed|null
     * @throws Exception
     */
    public static function LoadEntityByAlbum($album_id)
    {
        $q_meta = Doctrine_Query::create()
            ->select()
            ->from("AlbumMeta am")
            ->where("am.album_id = ?", $album_id);
        $o_meta = $q_meta->fetchOne();
        if(empty($o_meta))
        {
            throw new Exception("AlbumMeta::LoadEntityByAlbum: No entity found for identifier: " . $album_id);
        }
        return $o_meta;
    }

    /**
     * @return bool|Doctrine_Record|mixed|null
     */
    public static function LoadLastEntity()
    {
        $q_album_meta = Doctrine_Query::create()
            ->select()
            ->from("AlbumMeta am")
            ->orderBy("Id DESC")
            ->limit(1);
        $o_album_meta = $q_album_meta->fetchOne();
        return $o_album_meta;
    }
}