<?php

/**
 * AlbumMetaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlbumMetaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlbumMetaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AlbumMeta');
    }
}