<?php

/**
 * Songs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Songs extends BaseSongs
{

    public static function LoadEntity($id)
    {
        $songsTable = Doctrine_Core::getTable('Songs');
        $song = $songsTable->find($id);
        if($song == null || !isset($song))
        {
            throw new Exception("Songs::LoadEntity: Couldn't load the entity with the given identifier.");
        }
        return $song;
    }

    public static function SaveEntity($o_song)
    {
        if(empty($o_song))
        {
            throw new Exception("Songs::SaveEntity: The object passed to the function is empty.");
        }

        $song_id = empty($o_song['song_id']) ? null : $o_song['song_id'];
        $song_title = empty($o_song['song_title']) ? null : $o_song['song_title'];
        $song_length = empty($o_song['song_length']) ? null : $o_song['song_length'];
        $song_album_id = empty($o_song['song_album_id']) ? null : $o_song['song_album_id'];

        if(empty($song_title))
        {
            throw new Exception("Songs::SaveEntity: Song title can not be empty.");
        }
        if (empty($song_length))
        {
            throw new Exception("Songs::SaveEntity: Song length can not be empty.");
        }
        if(empty($song_album_id))
        {
            throw new Exception("Songs:SaveEntity: Song must be linked to an album. (Album id is empty)");
        }
    }
}