<style>
	body
	{
		width: 100%;
		
	}
	#left
	{
		width: 20%;
		float: left;
		margin-right: 3%;
		border-left: 1px solid black;
		border-right: 1px solid black;
		border-bottom: 1px solid black;
		box-shadow: 0px 4px 10px #888888;
	}
	#right
	{
		width: 75%;
		float: right;
	}
	.no-close .ui-dialog-titlebar-close
	{
		display: none;
	}
	.series_text
	{
		margin-left: 10px;
	}
	#div-list-series
	{
		margin-left: 10px;
		margin-right: 10px;
		display: flex;
		flex-wrap: wrap;
	}
</style>
<script type="text/javascript">
	$(document).ready(function (){
		
		loadSorterPanel();
		function loadSorterPanel()
		{
			$("#sort_panel").load("/default/sorter/show/type/series", function(){
				refreshserieslist();
			});
		}
		
		$(document).on("click", ".serie_link", function(){
			
			window.location.href = "/default/series/show/id/" + $(this).parent().find(":input").val();
		});
		
		
		$(document).on("click", ".quickview-serie-button", function(e){
		
				$("#dialog-showinfo").dialog('open');
	                $.ajax({
	                    type: "POST",
	                    url: "/default/index/getserieinfo/id_serie/" + $(this).parent().find(":input").val(),
	                    dataType: "json",
	                    success: function(data, status){
	                        if(data.result == "success")
	                        {
	                           $("#dialog-showinfo").dialog('option', 'title', data.srs_title);
	                           $("#d-title").html(data.srs_title);
	                           $("#d-description").html(data.srs_description);
	                        }
	                    }
	                });
			
		});
		
		
		$("#dialog-showinfo").dialog({
			dialogClass: "no-close",
            autoOpen: false,
            height: 600,
            width: 400,
            modal: true,
            draggable: false,
            resizable: false,
            
            title: "Informatie",
            buttons:[{
				text: "Annuleren",
				icons:{
					primary: "ui-icon-heart"
				},
				click:function(){
					$(this).dialog("close");
				}
			}]
		});
				
		$('.quickview-button').button();
		
		function refreshserieslist()
		{
			$("#div-list-series").load('/default/index/serieslist');
		}
	
	});
</script>
<div id="main">
	
	<div id="left">
		<div id="sort_panel">
			
		</div>
	</div>
	<div id="right">

		<h1 class="series_text">Series</h1>
		<div id="div-list-series">
		
		</div>
	</div>
	
</div>
<div id="dialog-showinfo">
	
</div>