<style>
	#picture{
		width: 100%; height: auto;
		margin-left: auto;
		margin-right: auto;
	}

	#left{
		float: left;
		width: 20%;
		margin-right: 3%;
		border-left: 1px solid black;
		border-right: 1px solid black;
		border-bottom: 1px solid black;
		box-shadow: 0px 4px 10px #888888;
	}
	
	#right{
		float:right;
		width: 76%;
	}
	
	#external_links
	{
		width:100%;
		display: inline;
		height: auto;
		margin-right: auto;
		margin-left: auto;
	}
	
	#imdb_link{
		margin-left: 5%;
		margin-right: 5%;
		width: 45%;
	}
	
	#rottentomatoes_link
	{
		width: 40%;
		margin-top: auto;
		margin-bottom: 2%;
	}
	#info_panel
	{
		margin-left: 5px;
	}

	#audio_languages, #subtitle_languages{
		display: none;
	}
	
	#toggleAudio, #toggleSubtitle
	{
		cursor: pointer;
	}
	
	.season
	{
		width: 100%;
		padding-bottom: 1%;
		padding-top: 1%;
		background-color: #34495E;
		cursor: pointer;
	}
	
	.full_season
	{
				margin-bottom: 2%;
	}
	
	.season_title{
		margin-left: 5%;
		color: #ECF0F1;
		font-size: 1.5em;
		width: 70%;
		display: inline;
		cursor: pointer;
	}
	
	.season_arrowdown
	{
		cursor: pointer;
		font-size: 1.5em;
		color: #ECF0F1;
		display: inline;
		margin-left: 1%;
		margin-bottom: 1%;
	}
	
	.season_info
	{
		display: none;
	}
	
</style>

<script type="text/javascript">
	$(document).ready(function(){
		
		$(document).on("click", ".episode", function(){
			
			$("#one_episode").load("/default/series/episodeinfo/idserie/" + $("#serie_id").val() + "/idseason/" + $(this).parent().parent().parent().find(".id_season").val() + "/idepisode/" + $(this).find(".id_episode").val() ,function(){
				$("#seriePanel").toggle();
			});
		});
		
		$(document).on("click", ".season", function(){
			if($(this).parent().find(".season_info").css("display") == "none")
			{
				$(this).find(".season_arrowdown").find("i").attr("class", "fa fa-cog fa-spin");
				$(this).parent().find(".season_info").load("/default/series/seasoninfo/idserie/" + $("#serie_id").val() + "/idseason/" + $(this).find(":input").val(), function(){
					$(this).parent().find(".season_arrowdown").find("i").attr("class", "fa fa-chevron-down");
					$(this).parent().find(".season_info").toggle();
					
				});
				
			}
			else
			{
				$(this).parent().find(".season_info").toggle();
			}
			
		});
		
		$(document).on("click", "#toggleAudio", function(){
			$("#audio_languages").toggle();
			if($("#audio_languages").css("display") == "none")
			{
				
				$("#toggleAudio").html("▼ Show Audio");
			}
			else
			{
				$("#toggleAudio").html("▲ Hide Audio");
			}
			
		});
		
		
		
		$(document).on("click", "#toggleSubtitle", function(){
			$("#subtitle_languages").toggle();
			if($("#subtitle_languages").css("display") == "none")
			{
				
				$("#toggleSubtitle").html("▼ Show Subtitles");
			}
			else
			{
				$("#toggleSubtitle").html("▲ Hide Subtitles");
			}
			
		});
	});
</script>

<?php
	$o_serie = $this->o_serie;
	$o_publishers_series = $this->o_publishers_series;
	$o_producers_series = $this->o_producers_series;
	$o_genres_series = $this->o_genres_series;
	$o_subtitles_series = $this->o_subtitles_series;
	$o_audio_series = $this->o_audio_series;
	$o_seasons_series = $this->o_seasons_series;
	if($o_serie != null){
?>
<div id="left">
	<img id="picture" alt="Plaatje van film: <?php echo $o_serie['srs_title']; ?>"src='/images/series/<?php echo $o_serie['srs_picture_url'] ?>'>
		<hr>
	<div id="info_panel">
		
		<h3><i class="fa fa-info-circle"></i> Information</h3>
		<input type=hidden id="serie_id" value="<?php echo $o_serie['id_serie']; ?>">
		<p id="franchise"><b>Franchise: </b> <?php echo $o_serie['Franchises']['fcs_title']; ?></p>
		<p id="publishers"><b>Publishers:</b> <?php foreach($o_publishers_series AS $item){ echo $item['Publishers']['pbs_name'] . ", ";} ?></p>
		<p id="producers"><b>Producers:</b> <?php foreach($o_producers_series AS $item) { echo $item['Producers']['pdr_name'] . ", ";} ?></p>
		<p id="genres"><b>Genres:</b> <?php foreach($o_genres_series AS $item){ echo $item['Genres']['gnr_name'] . ", ";}?></p>
		<p id="type"><b>Type:</b> <?php echo $o_serie['FilmserieType']['fst_name']; ?></p>
		<h4><i class="fa fa-globe"></i> Audio and subtitles</h3>
		<p id="toggleAudio">▼ Show Audio</p>
		<div id="audio_languages">
			<ul>
			<?php foreach($o_audio_series AS $item)
			{
				echo "<li>" . $item['Languages']['lgg_name'] . "</li>";
			} ?>
			</ul>
		</div>
		<p id="toggleSubtitle">▼ Show Subtitles</p>
		<div id="subtitle_languages">
			<ul>
			<?php foreach($o_subtitles_series AS $item)
			{
				echo "<li>" . $item['Languages']['lgg_name'] . "</li>";
			} ?>
			</ul>
		</div>
		<h3><i class="fa fa-link"></i> External Links</h3>
		<div id="external_links">
			<a href="<?php echo $o_serie['srs_imdb_link']; ?>"><img alt="IMDB logo" id="imdb_link" src="/images/external_links/imdb.png"></a>
			<a href="<?php echo $o_serie['srs_rottentomatoes_link']; ?>"><img alt="Het RottenTomatoes logo" id="rottentomatoes_link" src="/images/external_links/rottentomatoes.png"></a>
		</div>
	</div>
</div>

<div id='right'>
	<div id="one_episode">
		
	</div>
	<div id="seriePanel">
		<h1 id="title"><?php echo $o_serie['srs_title']; ?></h1>
		<p id="description"><?php echo $o_serie['srs_description']; ?></p>
	
		<h2>Seasons</h2>
			<div id="seasons">
				<?php
					$count = 0;
					foreach($o_seasons_series AS $item)
					{ $count = $count + 1;?>
						<div class="full_season">
							<div class='season'>
								<p class="season_arrowdown"><i class="fa fa-chevron-down"></i></p>
								<p class="season_title"><?php echo $count . " - " . $item['sss_name']; ?></p>
								<input type="hidden" class="id_season" value="<?php echo $item['id_season']; ?>">
							</div>
							<div class="season_info">
								
							</div>
						</div>
					<?php } ?>
			</div>
	</div>
	
</div>

<?php }else
	{
		echo "<h1>It looks like this movie wasn't a great hit.</h1>";
		echo "<p>This page has been deleted or did never exist</p>";
	} ?>