<?php
include "C:/wamp64/www/root3/application/repository/BaseRepository.php";
class SearchController extends Zend_Controller_Action
{
    function init()
    {
        $session = Zend_Session::namespaceGet("search_Namepsace");
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        $params = $this->getRequest()->getParams();

        if(empty($params))
        {
            $this->_redirect('/default/album/');
            die(0);
        }

        if(!isset($params['str']))
        {
            $this->_redirect('/default/album/');
            die(0);
        }

        $this->ar_results = BaseRepository::Search($params['str']);
    }

}