<head>
    <style>
        .table_space {
            padding: 10px 10px 10px 10px;
        }
    </style>
</head>
<?php
echo "<a href='/album/addalbum'>Add new album</a><br /> ";
echo "<a href='/default/songs/index'>Songs overview</a>";
?>
<table>
    <thead>
        <tr>
            <td class="table_space">Album id</td>
            <td class="table_space">Album title</td>
            <td class="table_space">Album Artist</td>
            <td class="table_space">Options</td>
        </tr>
    </thead>
    <tbody>
    <?php
foreach($this->ar_albums as $album)
{
    echo "<tr>";
        echo "<td class=\"table_space\">" . $album['id'] . "</td>";
        echo "<td class=\"table_space\">" . $album['title'] . "</td>";
        echo "<td class='table_space'>" . $album['artist'] . "</td>";
        echo "<td class=\"table_space\"> <a href='/album/albumDetails?id=" . $album['id'] . "'>Details</a> || <a href='/album/editAlbum?id=" . $album['id'] . "'>Edit</a> || <a href='/album/deleteAlbum?id=" . $album['id'] . "'>Delete</a>" . "</td>";
    echo "</tr>";
}
?>
    </tbody>
</table>
