<style>
	.no-close .ui-dialog-titlebar-close{
		display: none;
	}
	
	 #div-list-films
	{
		margin-left: 10px;
		margin-right: 10px;
		display: flex;
		flex-wrap: wrap;
	}
	.movies_text
	{
		margin-left: 10px;
	}
	
	#left{
		width: 20%;
		float: left;
		margin-right: 3%;
		border-left: 1px solid black;
		border-right: 1px solid black;
		border-bottom: 1px solid black;
		box-shadow: 0px 4px 10px #888888;
	}
	#right{
		width: 75%;
		float: right;
	}
</style>
<script type="text/javascript">

$(document).ready(function (){
	loadSorterPanel();
	function loadSorterPanel()
	{
		$("#sort_panel").load("/default/sorter/show/type/movies" ,function(){
			refreshmovieslist();
		});
	}
	
	$(document).on("click", ".movie_link", function(){
		
		window.location.href = "/default/films/show/id/" + $(this).parent().find(":input").val();
	});
	
	$(document).on("click", ".quickview-film-button", function(){
		
		$("#dialog-showinfo").dialog('open');
                $.ajax({
                    type: "POST",
                    url: "/default/index/getfilminfo/id_film/" + $(this).parent().find(":input").val(),
                    dataType: "json",
                    success: function(data, status){
                        if(data.result == "success")
                        {
                        	
                         $("#dialog-showinfo").dialog('option', 'title', data.mvs_title);
                         $("#d-title").html(data.mvs_title);
                         $("#d-description").html(data.mvs_description);
                           
                        }
                  	}
                   
                });
	});
	
	$("#dialog-showinfo").dialog({
		dialogClass: "no-close",
        autoOpen: false,
        height: 600,
        width: 400,
        modal: true,
        draggable: false,
        resizable: false,
        
        title: "Informatie",
        buttons:[{
			text: "Annuleren",
			icons:{
				primary: "ui-icon-heart"
			},
			click:function(){
				$(this).dialog("close");
            	
			}
		}]
	});

	$('.quickview-button').button();
	
	function refreshmovieslist()
	{
		$("#div-list-films").load('/default/index/filmlist');
	}
	
});
	
</script>
<div id="main">
	<div id="left">
		<div id="sort_panel">
			
		</div>
	</div>
	<div id="right">
		<h1 class="movies_text">Films</h1>
		<div id="div-list-films">
		
		</div>
	</div>
</div>
<div id="dialog-showinfo">
</div>