<script>
    $('#frm_add').submit(function(e) {
        e.preventDefault();
        $.post({
            url: <?php echo $this->url(array('action' =>'addsong','controller' => 'Songs')); ?>,
            data:$('#frm_add').serialize(),
            success: function(){
                //done
            }
        });
    });
</script>

<?php
$var = null;
if($_GET)
{
    if(isset($_GET['album']))
    {
        $var = $_GET['album'];
    }
}
?>

<form id="frm_add">
    <fieldset>
        <legend>Add new song</legend>
    </fieldset>
    <table>
        <tr>
            <td><label for="txt_song_title">Song title:</label></td>
            <td><input required type="text" id="txt_song_title" name="txt_song_title" placeholder="Clayman" /></td>
        </tr>
        <tr>
            <td><label for="txt_song_length">Song length:</label></td>
            <td><input required type="text" id="txt_song_length" name="txt_song_length" placeholder="3:20" /></td>
        </tr>
        <tr>
            <td><label for="slct_album">Appears on:</label></td>
            <td>
                <select name="slct_album" id="slct_album">
                    <?php
                        $albums = AlbumRepository::LoadAllAlbums();
                        foreach($albums as $album)
                        {
                            if($album['id'] == $var )
                                echo "<option value='" . $album['id'] . "' selected>" . $album['title'] . "</option>";

                            else
                                echo "<option value='" . $album['id'] . "'>" . $album['title'] . "</option>";
                        }
                    ?>
                </select>
            </td>
        </tr>
        <tr>
            <td><input type="submit" name="btn_submit" id="btn_submit" value="Save." /></td>
        </tr>
    </table>
</form>
<script type="text/javascript">