<head>
    <style>
        .table_space {
            padding: 10px 10px 10px 10px;
        }
    </style>
</head>
<?php

$song = $this->ar_songs;
$album = $this->ar_albums;

?>

<table>
    <thead>
        <tr>
            <th class="table_space">ID</th>
            <th class="table_space">Title</th>
            <th class="table_space">Length</th>
            <th class="table_space">On album:</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="table_space"><?php echo $song->id; ?></td>
            <td class="table_space"><?php echo $song->title; ?></td>
            <td class="table_space"><?php echo $song->length; ?></td>
            <td class="table_space"><a href="<?php echo '/default/album/albumDetails?id='.$album->id; ?>"><?php echo $album->title ?></a></td>
        </tr>
    </tbody>
</table>
<a href="/default/songs/editSong?id=<?php echo $song->id; ?>">Edit</a>
