<body>
<h2>Gebruikersnaam vergeten</h2>

U heeft aangegeven dat u uw gebruikersnaam bent vergeten. </br>
Uw gebruikersnaam is:<?php echo $this->user ?></br>
Om uw admin omgeving zo goed mogelijk beschermt te houden raden wij u aan zo snel mogelijk uw gebruikersnaam en wachtwoord te veranderen in het admingedeelte van de software.</br>
</br>
Indien er vragen zijn kunt u met ons contact opnemen via het contactformulier of de chat op de website of via e contactgegevens onderin deze mail.</br>
</br>
Met vriendelijke groet,</br>
Quality Retail Solutions
	
</body>