<body>
<h2>Wachtwoord vergeten</h2>

U heeft aangegeven dat u het wachtwoord bent vergeten dat bij uw gebruikersnaam hoort. </br>
Uw nieuwe wachtwoord is:<?php echo $this->password; ?></br>
Om uw admin omgeving zo goed mogelijk beschermt te houden raden wij u aan zo snel mogelijk uw wachtwoord te veranderen in het admingedeelte van de software.</br>
</br>
Indien er vragen zijn kunt u met ons contact opnemen via het contactformulier of de chat op de website of via e contactgegevens onderin deze mail.</br>
</br>
Met vriendelijke groet,</br>
Quality Retail Solutions
</body>